### ISSUE TITLE
server side code

### ISSUE THREAD

**Issue by mattwoolnough** [ak1394/react-native-login-example#1]
This example doesn't appear to work without some server side code.
The oauth code is returned to a URL, but that's the end of the story.

Can you provide any code, or info on what's required server side to get the code or access token back to the client?

**Comment by ak1394** [comment]
Please check out this post https://medium.com/@ak1394/simple-social-login-for-react-native-apps-71279bf80ffc

**Comment by mattwoolnough** [comment]
The detail I was overlooking was the "number of networked services" deployed in the Server Setup section.  
thanks!
